#create a simple calculator using tkinter
import tkinter as tk
root=tk.Tk()
root.title("Simple Calculator")
root.geometry("250x250")
root.resizable(False,False)
e1=tk.Entry(root,width=30,font=("Arial",20),bg="#353333",fg="#f1efef",justify="right").pack(padx=2,pady=2)
top_frame=tk.Frame(root,width=30)
top_frame.pack(fill="both",expand="True")
for i in range(3):
    top_frame.columnconfigure(i,weight=1,uniform="button")
top_frame.rowconfigure(0,weight=1)
bt1=tk.Button(top_frame,text="AC",fg="#eeeaea",bg="#616161",font=("Arial",12))
bt1.grid(row=0,column=0,sticky="nsew")
bt2=tk.Button(top_frame,text="+/-",fg="#eeeaea",bg="#616161",font=("Arial",12))
bt2.grid(row=0,column=1,sticky="nsew")
bt3=tk.Button(top_frame,text="%",fg="#eeeaea",bg="#616161",font=("Arial",12))
bt3.grid(row=0,column=2,sticky="nsew")
bt4=tk.Button(top_frame,text="+",fg="#eeeaea",bg="#dfbd25",font=("Arial",12))
bt4.grid(row=0,column=3,sticky="nsew")
sec_frame=tk.Frame(root)
sec_frame.pack(fill="both",expand="True")
for i in range(3):
    sec_frame.columnconfigure(i,weight=1,uniform="button")
sec_frame.rowconfigure(1,weight=1)
bt5=tk.Button(sec_frame,text="7",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt5.grid(row=1,column=0,sticky="nsew")
bt6=tk.Button(sec_frame,text="8",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt6.grid(row=1,column=1,sticky="nsew")
bt7=tk.Button(sec_frame,text="9",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt7.grid(row=1,column=2,sticky="nsew")
bt8=tk.Button(sec_frame,text="X",fg="#eeeaea",bg="#dfbd25",font=("Arial",12))
bt8.grid(row=1,column=3,sticky="nsew")
third_frame=tk.Frame(root)
third_frame.pack(fill="both",expand="True",)
for i in range(3):
    third_frame.columnconfigure(i,weight=1,uniform="button")
third_frame.rowconfigure(2,weight=1)
bt9=tk.Button(third_frame,text="4",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt9.grid(row=2,column=0,sticky="nsew")
bt10=tk.Button(third_frame,text="5",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt10.grid(row=2,column=1,sticky="nsew")
bt11=tk.Button(third_frame,text="6",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt11.grid(row=2,column=2,sticky="nsew")
bt12=tk.Button(third_frame,text="-",fg="#eeeaea",bg="#dfbd25",font=("Arial",12))
bt12.grid(row=2,column=3,sticky="nsew")
fourth_frame=tk.Frame(root)
fourth_frame.pack(fill="both",expand="True")
for i in range(3):
    fourth_frame.columnconfigure(i,weight=1,uniform="button")
fourth_frame.rowconfigure(3,weight=1)
bt13=tk.Button(fourth_frame,text="1",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt13.grid(row=3,column=0,sticky="nsew")
bt14=tk.Button(fourth_frame,text="2",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt14.grid(row=3,column=1,sticky="nsew")
bt15=tk.Button(fourth_frame,text="3",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt15.grid(row=3,column=2,sticky="nsew")
bt16=tk.Button(fourth_frame,text="+",fg="#eeeaea",bg="#dfbd25",font=("Arial",12))
bt16.grid(row=3,column=3,sticky="nsew")
last_frame=tk.Frame(root)
last_frame.pack(fill="both",expand="True")
for i in range(3):
    last_frame.columnconfigure(i,weight=1,uniform="button")
last_frame.rowconfigure(4,weight=1)
bt17=tk.Button(last_frame,text="0",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt17.grid(row=4,column=0,sticky="nsew")
bt18=tk.Button(last_frame,text=".",fg="#eeeaea",bg="#837E7E",font=("Arial",12))
bt18.grid(row=4,column=1,sticky="nsew")
bt19=tk.Button(last_frame,text="=",fg="#eeeaea",bg="#dfbd25",font=("Arial",12))
bt19.grid(row=4,column=2,sticky="nsew")

root.mainloop()